---
name: ⚒️ CI

on:
  pull_request: {}
  push:
    branches:
      - master

permissions:
  contents: read # minimal required permissions to clone repo

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
      - name: Build gem
        run: gem build --strict --verbose *.gemspec
